# Generated by Django 5.1.3 on 2024-12-03 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_duration',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество гостей'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец брони'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='booking.table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_status',
            field=models.CharField(choices=[('Available', 'Доступен'), ('Reserved', 'Забронирован')], default='Available', max_length=255, verbose_name='Статус бронирования стола'),
        ),
    ]
