# Generated by Django 5.1.3 on 2024-12-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_reservation_guests_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guests_amount',
            field=models.CharField(choices=[('1-2', '1-2'), ('3-4', '3-4'), ('4+', '4+')], default='1-2', verbose_name='Количество гостей'),
        ),
    ]
