# Generated by Django 5.1.3 on 2024-12-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_reservation_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('Активна', 'Активна'), ('Истекла', 'Истекла'), ('Отменена', 'Отменена')], default='Активна', verbose_name='Статус брони'),
        ),
    ]
